# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/007a5eb0-7fd8-45b9-b4b2-799135d28292/transcription
Content-Type: application/json

{
  "prompt": "clean architecture, DDD"
}

###

# @name generate-ai-complete
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "007a5eb0-7fd8-45b9-b4b2-799135d28292",
  "template": "Gere um resumo sucinto da transcrição do vídeo informado a seguir: '''{transcription}''' ",
  "temperature": 0.5
}
